name = "attack-sota"
compatibility_date = "2026-05-29"
pages_build_output_dir = "cloudflare-dist"

[vars]
ALLOWED_ORIGINS = "https://symmetric-cryptanalysis-index.netlify.app https://zhangjn.com https://www.zhangjn.com"

[[d1_databases]]
binding = "DB"
database_name = "attack-sota"
database_id = "612c04e9-baf7-4875-8242-8fbecb907fef"
